# TODO: Should be be smth else
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql-deployment
  namespace: yaml
spec:
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/azure-sql-edge
        ports:
          - containerPort: 1433
        env:
        - name: MSSQL_PID
          value: "Developer"
        - name: ACCEPT_EULA
          value: "Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: sa-password
        volumeMounts:
          - mountPath: /var/opt/mssql/data
            name: mssqldb
      volumes:
        - name: mssqldb
          persistentVolumeClaim:
            claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-clusterip-service
  namespace: yaml
spec:
  type: ClusterIP
  selector:
    app: mssql
  ports:
  - name: default
    protocol: TCP
    port: 1433
    targetPort: 1433
