apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
  namespace: yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
        - name: platform-service
          image: maksimsech/platform-service:latest-arm
          ports:
          - containerPort: 81
          env:
          - name: HttpCommandSyncService_BaseAddress
            valueFrom:
              configMapKeyRef:
                name: command-configmap
                key: base-url
          - name: SqlConnectionString__Server
            valueFrom:
              configMapKeyRef:
                name: mssql-configmap
                key: database-url
          - name: SqlConnectionString__UserId
            value: sa
          - name: SqlConnectionString__Password
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: sa-password
          - name: RabbitMq__Host
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: host
          - name: RabbitMq__Port
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: port
          - name: Ports__Http
            valueFrom:
              configMapKeyRef:
                name: platform-configmap
                key: http-port
          - name: Ports__Grpc
            valueFrom:
              configMapKeyRef:
                name: platform-configmap
                key: grpc-port
---
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-service
  namespace: yaml
spec:
  type: ClusterIP
  selector:
    app: platform-service
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
  - name: grpc
    protocol: TCP
    port: 81
    targetPort: 81
