apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-service
  template:
    metadata:
      labels:
        app: command-service
    spec:
      containers:
        - name: command-service
          image: maksimsech/command-service:latest
          env:
          - name: RabbitMq__Host
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: host
          - name: RabbitMq__Port
            valueFrom:
              configMapKeyRef:
                name: rabbitmq-configmap
                key: port
          - name: Grpc__Platform
            valueFrom:
              configMapKeyRef:
                name: platform-configmap
                key: grpc-uri
---
apiVersion: v1
kind: Service
metadata:
  name: command-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: command-service
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
  