apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-service
  template:
    metadata:
      labels:
        app: platform-service
    spec:
      containers:
        - name: platform-service
          image: maksimsech/platform-service:latest
          env:
          - name: SqlConnectionString__Server
            valueFrom:
              configMapKeyRef:
                name: mssql-configmap
                key: database-url
          - name: SqlConnectionString__UserId
            value: sa
          - name: SqlConnectionString__Password
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: sa-password
---
apiVersion: v1
kind: Service
metadata:
  name: platform-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: platform-service
  ports:
  - name: default
    protocol: TCP
    port: 80
    targetPort: 80
